[package]
name = "demo"
version = "0.1.0"
edition = "2018"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[features]
pf-gl = ["pathfinder_demo/pf-gl"]
pf-no-simd = ["pathfinder_simd/pf-no-simd"]

[dependencies]
color-backtrace = "0.1"
gl = "0.6"
nfd = "0.0.4"
pretty_env_logger = "0.3"
sdl2 = "0.32"
sdl2-sys = "0.32"

[dependencies.pathfinder_demo]
path = "../common"

[dependencies.pathfinder_geometry]
path = "../../geometry"

[dependencies.pathfinder_gl]
path = "../../gl"

[dependencies.pathfinder_gpu]
path = "../../gpu"

[dependencies.pathfinder_simd]
path = "../../simd"

[target.'cfg(target_vendor = "apple")'.dependencies]
foreign-types = "0.3"
metal = "0.14"

[target.'cfg(target_vendor = "apple")'.dependencies.pathfinder_metal]
path = "../../metal"

[target.'cfg(all(not(windows), any(not(target_vendor = "apple"), target_os = "macos")))'.dependencies]
jemallocator = "0.1"
